version: '3.8'

services:

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend/build:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build: ./backend
    image: app
    container_name: brainns-api
    ports:
      - 5001:5001
    volumes:
      - ./backend:/usr/src/app #local:container
      - ./image-repository:/usr/src/image-repository
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
      - mysqlDB
  # command: python app.py run -h 0.0.0.0 -p 5001
    command: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mysqlDB:3306 -- python app.py run -h 0.0.0.0 -p 5001"

  worker:
    image: app
    container_name: brainns-worker
    volumes:
      - ./backend:/usr/src/app
      - ./image-repository:/usr/src/image-repository
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Access to all GPUs for availablity check
              capabilities: [gpu]
    command: python worker.py


  redis:
    image: redis
    container_name: brainns-redis
    volumes:
      - ./redis-data:/data


  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: brainns-dashboard
    ports:
      - 9181:9181
    depends_on:
      - redis
    command: rq-dashboard --redis-url redis://redis:6379


  mysqlDB:
    image: mysql:latest
    container_name: brainns-mysqlDB
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password