version: '3.8'

######Production Settings#####
# Frontend added
# User added to each container
# Removed Docker Socket mount
# Removed GPU Access
# Restart Policy added


services:

  frontend:
    build: ./frontend
    image: frontend
    container_name: brainns-frontend
    user: 1050:1050
    ports:
      - "5000:3000"
    command: node build 
    restart: unless-stopped

  api:
    build: ./backend
    image: app
    container_name: brainns-api
    user: 1050:1050
    ports:
      - 5001:5001
    volumes:
      - ./backend:/usr/src/app #local:container
      - ./image-repository:/usr/src/image-repository
    # - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
      - mysqlDB
    # command: python app.py run -h 0.0.0.0 -p 5001
    command: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mysqlDB:3306 -- python app.py run -h 0.0.0.0 -p 5001"
    restart: unless-stopped


  worker:
    image: app
    container_name: brainns-worker
    user: 1050:1050
    volumes:
      - ./backend:/usr/src/app
      - ./image-repository:/usr/src/image-repository
    #  - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
    command: python worker.py
    restart: unless-stopped


  redis:
    image: redis
    container_name: brainns-redis
    user: 1050:1050
    volumes:
      - ./redis-data:/data
    restart: unless-stopped


  mysqlDB:
    image: mysql:latest
    container_name: brainns-mysqlDB
    user: 1050:1050
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    restart: unless-stopped