version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build: ./backend
    image: app
    container_name: api
    ports:
      - 5000:5000
    command: python app.py run -h 0.0.0.0
    # command: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh mysqlDB:3306 -- python app.py run -h 0.0.0.0"
    volumes:
      - ./backend:/usr/src/app #local:container
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
      - mysqlDB

  worker:
    image: app
    container_name: worker
    command: python worker.py
    volumes:
      - ./backend:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # For prints
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Access to all GPUs for availablity check
              capabilities: [gpu]

  redis:
    image: redis
    container_name: redis-queue
    volumes:
      - ./redis-data:/data


  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - 9181:9181
    command: rq-dashboard --redis-url redis://redis:6379
    depends_on:
      - redis

  mysqlDB:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql