version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build: ./backend
    image: app
    container_name: api
    ports:
      - 5000:5000
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./backend:/usr/src/app #local:container
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    image: app
    container_name: worker
    command: python app.py run_worker
    volumes:
      - ./backend:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock  # Bind the Docker socket
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-queue
    volumes:
      - ./backend/redis:/data


  dashboard:
    build: ./backend/dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - 9181:9181
    command: rq-dashboard --redis-url redis://redis:6379
    depends_on:
      - redis